const {
  MONGO_URL = 'mongodb://localhost:27017/newBorndb',
  PORT = 3005,
  PATH_TO_FILE,
  PROJECT_ID,
  BUCKET_NAME,
  PASSWORD_EMAIL_ACCOUNT,
  EMAIL_ACCOUNT,
} = process.env;

module.exports = {
  PORT, PATH_TO_FILE, PROJECT_ID, BUCKET_NAME, PASSWORD_EMAIL_ACCOUNT, EMAIL_ACCOUNT, MONGO_URL,
};
