const {
  PORT = 3005,
  TOKEN_INSTAGRAM_PROFILE,
  PATH_TO_FILE,
  PROJECT_ID,
  BUCKET_NAME,
  PASSWORD_EMAIL_ACCOUNT,
  EMAIL_ACCOUNT,
} = process.env;

module.exports = {
  PORT, TOKEN_INSTAGRAM_PROFILE, PATH_TO_FILE, PROJECT_ID, BUCKET_NAME, PASSWORD_EMAIL_ACCOUNT, EMAIL_ACCOUNT,
};
